export function ArchitecturePage() {
  return <>
    <div className="page-intro compact"><p className="kicker">SYSTEM MODEL</p><h1>Interpretation is not<br /><em>authorization.</em></h1><p className="hero-sub">VETA keeps the probabilistic layer useful and the transaction boundary deterministic.</p></div>
    <section className="architecture-flow"><FlowNode label="INTENT / EVIDENCE" detail="human request and source material" /><FlowArrow /><FlowNode label="QVAC LOCAL" detail="semantic interpretation + tools" accent="model" /><FlowArrow /><FlowNode label="PROVENANCE" detail="source, trust, extraction state" /><FlowArrow /><FlowNode label="AUTHORITY ENGINE" detail="field-specific expected values" accent="authority" /><div className="flow-split"><div><FlowNode label="PROPOSED TX" detail="candidate execution" /><FlowArrow /><FlowNode label="EVM DECODER" detail="viem transfer decoding" /><FlowArrow /><FlowNode label="T0 ONCHAIN" detail="execution reality" accent="onchain" /></div><div className="flow-plus">+</div><div><FlowNode label="AUTHORITY" detail="what should execute" accent="authority" /></div></div><FlowArrow /><FlowNode label="SAFETY KERNEL" detail="exact comparison; no model decision" accent="kernel" /><FlowArrow /><div className="flow-verdicts"><span className="approve">APPROVE</span><span className="block">BLOCK</span><span className="review">REVIEW</span></div></section>
    <section className="principles-grid"><div className="principle"><span>01</span><h2>QVAC interprets.</h2><p>Local QVAC extracts payment intent and selects registered tools. It can be wrong, malformed, or manipulated.</p><div className="responsibilities"><b>✓ interpret intent</b><b>✓ orchestrate tools</b><b className="no">× authorize payments</b><b className="no">× override authority</b></div></div><div className="principle"><span>02</span><h2>VETA verifies.</h2><p>Evidence is assigned trust and field-specific authority. T0 describes what will execute, never what should execute.</p><div className="tier-stack"><span className="tier t0">T0 · ONCHAIN / execution reality</span><span className="tier t1">T1 · AUTHORITY / organizational</span><span className="tier t2">T2 · SUPPORTING / corroboration</span><span className="tier t3">T3 · UNTRUSTED / free-form</span></div></div><div className="principle boundary"><span>03</span><h2>Code decides.</h2><p>Only deterministic evidence resolution, decoding, and Safety Kernel checks can produce the final state.</p><strong>AI may interpret.<br />AI may orchestrate.<br />AI may fail.<br /><em>AI cannot authorize.</em></strong></div></section>
    <section className="sepolia-card"><div><p className="kicker">REAL NETWORK CHECK</p><h2>Sepolia · controlled experiment</h2><p>Read-only validation of a public ERC-20 transfer. The authority fixture is controlled test evidence, not a claim about the historical request.</p><a href="https://sepolia.etherscan.io/tx/0x3518fd656c282cb7f9aaf8ab1e61b86f0344d43980d7b0da730a4a22efaeea91" target="_blank" rel="noreferrer">View transaction ↗</a></div><div className="sep-details"><span>TX <code>0x3518fd65...efaeea91</code></span><span>FUNCTION <code>transfer(address,uint256)</code></span><span>OBSERVED <strong>25 LINK</strong></span><span>RECIPIENT <code>0x3eB2...C967</code></span><span className="approve-text">controlled match → APPROVE</span><span className="block-text">controlled mismatch → BLOCK</span></div></section>
  </>;
}

function FlowNode({ label, detail, accent = "" }: { label: string; detail: string; accent?: string }) { return <div className={`flow-node ${accent}`}><strong>{label}</strong><span>{detail}</span></div>; }
function FlowArrow() { return <div className="flow-arrow">↓</div>; }
