import type { M7Artifact } from "../../src/ui/m7-artifact";

const percent = (value: number | null) => value === null ? "N/A" : `${(value * 100).toFixed(2)}%`;
const modeLabels: Record<string, string> = { DETERMINISTIC: "Deterministic", MOCK_QVAC: "Mock QVAC", REAL_QVAC: "Real QVAC", REAL_NETWORK: "Real network" };

export function ReliabilityLab({ artifact }: { artifact: M7Artifact }) {
  const headline = [
    ["Unsafe approval rate", artifact.metrics.unsafeApprovalRate, "safety"],
    ["Safe approval rate", artifact.metrics.safeApprovalRate, "utility"],
    ["Verdict accuracy", artifact.metrics.verdictAccuracy, "accuracy"],
    ["Model failure containment", artifact.metrics.modelFailureContainmentRate, "containment"],
  ] as const;
  return <>
    <div className="page-intro compact"><p className="kicker">M7 · BALANCED RELIABILITY</p><h1>Safety <em>and</em> utility.</h1><p className="hero-sub">A balanced read of 28 adversarial scenarios and 8 safe controls. No opaque score.</p></div>
    <section className="metric-grid">{headline.map(([label, value, tone]) => <div className={`metric-card ${tone}`} key={label}><span className="metric-label">{label}</span><strong>{percent(value)}</strong><span className="metric-rule" /></div>)}</section>
    <section className="lab-layout"><div className="panel"><div className="section-label">DATASET <span>predeclared labels</span></div><div className="dataset-counts"><div><strong>{artifact.dataset.total}</strong><span>scenarios</span></div><div><strong>{artifact.dataset.unsafe}</strong><span>unsafe</span></div><div><strong>{artifact.dataset.safe}</strong><span>safe</span></div></div><div className="outcome-bars"><OutcomeBar label="APPROVE" count={artifact.counts.approvals} total={artifact.dataset.total} tone="approve" /><OutcomeBar label="BLOCK" count={artifact.counts.blocks} total={artifact.dataset.total} tone="block" /><OutcomeBar label="REVIEW" count={artifact.counts.reviews} total={artifact.dataset.total} tone="review" /></div></div><div className="panel warning-panel"><div className="section-label">FAIL-CLOSED BEHAVIOR <span>interpretation</span></div><div className="failure-flow"><span>MODEL FAILURE</span><b>↓</b><span>VERIFICATION INCOMPLETE</span><b>↓</b><strong>REVIEW</strong><b>↓</b><span>NO AUTHORIZATION</span></div><p>VETA returns <code>REVIEW</code> when authority or execution cannot be established. A high review rate is not automatically a safety failure.</p></div></section>
    <section className="panel real-qvac"><div className="section-label">REAL LOCAL MODEL <span>not a mock</span></div><div className="qvac-head"><div><span className="metric-label">Model</span><strong>{artifact.runtime.qvacModel}</strong></div><div><span className="metric-label">Runs</span><strong>{artifact.byExecutionMode.REAL_QVAC.scenarios}</strong></div><div><span className="metric-label">Accuracy</span><strong>{percent(artifact.byExecutionMode.REAL_QVAC.accuracy)}</strong></div><div><span className="metric-label">Average latency</span><strong>{artifact.byExecutionMode.REAL_QVAC.averageLatencyMs === null ? "N/A" : `${(artifact.byExecutionMode.REAL_QVAC.averageLatencyMs / 1000).toFixed(1)} s`}</strong></div></div><div className="qvac-callout"><strong>{artifact.counts.modelFailures} observed model failures.</strong><span>{artifact.counts.unsafeApprovals} unsafe approvals.</span></div></section>
    <section className="panel"><div className="section-label">CONSERVATIVE DEGRADATIONS <span>expected BLOCK → actual REVIEW</span></div><div className="degradation-list">{artifact.conservativeDegradations.map((item) => <div className="degradation" key={item.scenarioId}><strong>{item.scenarioId}</strong><span>Expected <b>BLOCK</b></span><span>Actual <b className="review-text">REVIEW</b></span><small>{item.description}</small></div>)}</div></section>
    <section className="panel"><div className="section-label">EXECUTION MODE <span>preserved distinctions</span></div><div className="mode-list">{Object.entries(artifact.byExecutionMode).filter(([, value]) => value.scenarios > 0).map(([mode, summary]) => <div className="mode-row" key={mode}><strong>{modeLabels[mode] ?? mode}</strong><span>{summary.scenarios} scenarios</span><span>{percent(summary.accuracy)} accuracy</span><div className="mode-track"><i style={{ width: `${(summary.accuracy ?? 0) * 100}%` }} /></div><span>{summary.approvals} approve · {summary.blocks} block · {summary.reviews} review</span></div>)}</div></section>
    <p className="artifact-note">Source: <code>artifacts/m7-balanced-reliability.json</code> · generated {new Date(artifact.generatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}</p>
  </>;
}

function OutcomeBar({ label, count, total, tone }: { label: string; count: number; total: number; tone: string }) { return <div className="outcome-row"><span>{label}</span><div className="outcome-track"><i className={tone} style={{ width: `${(count / total) * 100}%` }} /></div><strong>{count}</strong></div>; }
